name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [trigger-deploy] # Listen for the custom dispatch event
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: leoplureodon/fe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: leoplureodon/leoplureodon-dev
          token: ${{ secrets.GITHUB_TOKEN }}
          path: private-repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: |
          cd private-repo
          npm install

      - name: Build React app
        env:
          REACT_APP_API_ADDRESS: ${{ secrets.REACT_APP_API_ADDRESS }}
          CI: false # Don't treat warnings as errors
        run: |
          cd private-repo
          npm run build --verbose

      - name: Clean up existing worktrees
        run: |
          git worktree prune
          git worktree list
          git worktree remove github-pages-deploy-action-temp-deployment-folder --force || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: private-repo/build
          publish_branch: gh-pages
