name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [trigger-deploy] # Listen for the custom dispatch event
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: leoplureodon/fe
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: leoplureodon/leo-dev-2
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          path: private-repo
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: |
          cd private-repo
          npm install

      - name: Build React app
        env:
          VITE_API_ADDRESS: ${{ secrets.VITE_API_ADDRESS }}
          VITE_SOME_KEY: ${{ secrets.VITE_SOME_KEY }}
          CI: false # Don't treat warnings as errors
        run: |
          cd private-repo
          npm run build --verbose

      - name: Clean up existing worktrees
        run: |
          git worktree prune
          git worktree list
          if [ -d "github-pages-deploy-action-temp-deployment-folder" ]; then
            git worktree remove github-pages-deploy-action-temp-deployment-folder --force
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: private-repo/dist
          publish_branch: gh-pages
